
DELETE FROM [dbo].[ApplicationSettings]
DELETE FROM [dbo].[AspNetRoleClaims]
DELETE FROM [dbo].[AspNetUserTokens]
DELETE FROM [dbo].[AspNetUserRoles]
DELETE FROM [dbo].[AspNetUserClaims]
DELETE FROM [dbo].[AspNetUserLogins]
DELETE FROM [dbo].[AspNetRoles]
DELETE FROM [dbo].[Reviews]
DELETE FROM [dbo].[OrderItems]
DELETE FROM [dbo].[Orders]
DELETE FROM [dbo].[CartItems]
DELETE FROM [dbo].[Carts]
DELETE FROM [dbo].[AspNetUsers]
DELETE FROM [dbo].[Products]
DELETE FROM [dbo].[Categories]